#!/bin/bash

## Description: Run phpcs checks on code
## Usage: phpcs
## Example: "ddev phpcs path/to/module/folder" or "ddev phpcs /path/to/module/folder -a"

vendor/bin/phpcs --standard=Drupal,DrupalPractice --extensions=php,module,inc,install,test,profile,theme,scss,yml,twig,md --ignore=vendor --ignore='*/node_modules/*' --colors $@

#> vendor/bin/phpcs --standard=Drupal,DrupalPractice --extensions=php,module,inc,install,test,profile,theme,scss,yml,twig web/modules/custom web/themes/custom tests/behat -a --ignore='*/node_modules/*' 'web/themes/custom/um_base'
